const PROMOTION_NUM = 100;
const DEFAULT_PAGE_SIZE = 10;
const DEFAULT_PAGE_NUM = 1;
const PROMOTION_NAME = "promotions";

module.exports = {
    PROMOTION_NUM: PROMOTION_NUM,
    DEFAULT_PAGE_SIZE: DEFAULT_PAGE_SIZE,
    DEFAULT_PAGE_NUM: DEFAULT_PAGE_NUM,
    PROMOTION_NAME: PROMOTION_NAME
};